# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/ner/00_ner_utils.ipynb.

# %% auto 0
__all__ = ['EduNER', 'JobNER']

# %% ../../nbs/ner/00_ner_utils.ipynb 2
from ..imports import *
from ..chains import *
from ..utils import *
from pydantic import BaseModel, Field
from langchain.output_parsers import PydanticOutputParser

# %% ../../nbs/ner/00_ner_utils.ipynb 4
class EduNER(BaseModel):
    degree: str = Field(description="The degree of the education.", default=None)
    major: str = Field(description="The major of the education.", default=None)
    school: str = Field(description="The school of the education.", default=None)
    date: str = Field(description="The date of the education.", default=None)


class JobNER(BaseModel):
    role: str = Field(description="The role of the job.", default=None)
    company: str = Field(description="The company of the job.", default=None)
    duration: str = Field(description="The duration of the job.", default=None)
